# This workflow will do a clean install of node dependencies, build the source code, run tests,
# and create a zip with required files for publishing to Chrome Web Store

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build
    - run: npm test --if-present
    - run: npm run zip
    - name: Chrome Addon Action
      uses: trmcnvn/chrome-addon@v2
      with:
        zip: release.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

